#ifndef __FLB_LBRT_ERROR_H__
#define __FLB_LBRT_ERROR_H__

enum {
  PortBaseErr = -1000,
  PortExistsErr,
  PortNotExistErr,
  PortNoMasterErr,
  PortCounterErr,
  PortMapErr,
  PortZoneErr,
  PortNoRealDevErr,
  PortPropExistsErr,
  PortPropNotExistsErr,
};

enum {
  VLAN_BASE_ERR = -2000,
  VLAN_EXISTS_ERR,
  VLAN_NOT_EXIST_ERR,
  VLAN_RANGE_ERR,
  VLAN_ADD_BRP_ERR,
  VLAN_MP_EXIST_ERR,
  VLAN_PORT_PHY_ERR,
  VLAN_PORT_EXIST_ERR,
  VLAN_PORT_TAGGED_ERR,
  VLAN_NO_PORT_ERR,
  VLAN_PORT_CREATE_ERR,
  VLAN_ZONE_ERR,
};

enum {
  L2_BASE_ERR = -3000,
  L2_SAME_FDB_ERR,
  L2_OIF_ERR,
  L2_NO_FDB_ERR,
  L2_VXATTR_ERR,
  L2_ALLOC_ERR,
};

enum {
  NEIGH_BASE_ERR = -4000,
  NEIGH_EXISTS_ERR,
  NEIGH_OIF_ERR,
  NEIGH_NO_ENT_ERR,
  NEIGH_RANGE_ERR,
  NEIGH_HOST_RT_ERR,
  NEIGH_MAC_ERR,
  NEIGH_TUN_ERR,
};

enum {
  RT_ERR_BASE = -5000,
  RT_EXISTS_ERR,
  RT_NH_ERR,
  RT_NOENT_ERR,
  RT_RANGE_ERR,
  RT_MOD_ERR,
  RT_TRIE_ADD_ERR,
  RT_TRIE_DEL_ERR,
};

enum {
  ZONE_BASE_ERR = -6000,
  ZONE_EXISTS_ERR,
  ZONE_NOT_EXIST_ERR,
  ZONE_NUMBER_ERR,
  ZONE_ALLOC_ERR,
};

enum {
  RULE_BASE_ERR = -7000,
  RULE_UNKNOWN_SERVICE_ERR,
  RULE_UNKNOWN_EP_ERR,
  RULE_EXISTS_ERR,
  RULE_ALLOC_ERR,
  RULE_NOT_EXISTS_ERR,
  RULE_EP_COUNT_ERR,
  RULE_TUPLE_ERR,
  RULE_ARGS_ERR,
  RULE_EP_NOT_EXIST_ERR,
};

enum {
  L3_BASE_ERR = -8000,
  L3_ADDR_ERR,
  L3_OBJ_ERR,
};

enum {
  CI_BASE_ERR = -90000,
  CI_MOD_ERR,
  CI_STATE_ERR,
};

enum {
  POL_BASE_ERR = -100000,
  POL_MOD_ERR,
  POL_INFO_ERR,
  POL_ATTACH_ERR,
  POL_NO_EXIST_ERR,
  POL_EXISTS_ERR,
  POL_ALLOC_ERR,
};

enum {
  MIRR_BASE_ERR = -101000,
  MIRR_MOD_ERR,
  MIRR_INFO_ERR,
  MIRR_ATTACH_ERR,
  MIRR_NO_EXIST_ERR,
  MIRR_EXISTS_ERR,
  MIRR_ALLOC_ERR,
};

enum {
  SESS_BASE_ERR = -102000,
  SESS_MOD_ERR,
  SESS_NO_EXIST_ERR,
  SESS_EXISTS_ERR,
  SESS_ULCL_EXIST_ERR,
  SESS_ULCL_NUM_ERR,
  SESS_ULCL_NO_EXIST_ERR,
};

enum {
  DP_ERR_BASE = -103000,
  DP_WQ_UNK_ERR,
};

#endif /* __FLB_LBRT_ERROR_H__ */